version: '0.0.{build}'

init:
  - ps: >-
      if($env:appveyor_repo_tag -eq 'True') {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
      }

configuration:
  - Debug
  - Release

environment:
  global:
    PYTHON: "C:\\Python36"

  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017    
    arch: x86
    platform: Win32
    visual_studio: Visual Studio 15 2017
    compiler_toolset: v141
    gtest: 1.7.0

  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    arch: x86_64
    platform: x64
    visual_studio: Visual Studio 16 2019
    compiler_toolset: v142
    gtest: 1.10.0

install:
  - "SET PATH=%PYTHON%;%PYTHON%/Scripts/;%PATH%"
  - pip.exe install conan
  - conan user
  - conan remote add systelab-bintray https://api.bintray.com/conan/systelab/conan
  - conan --version

before_build:
  - conan export-pkg WebSocketsAdapterInterface/conanfile.py WebSocketsAdapterInterface/%APPVEYOR_BUILD_VERSION%@systelab/stable -s build_type=%CONFIGURATION% -s compiler.toolset=%COMPILER_TOOLSET% -s arch=%ARCH%
  - md build
  - cd build
  - conan install ../WebSocketsAdapterTestUtilities -s build_type=%CONFIGURATION% -s compiler.toolset=%COMPILER_TOOLSET% -s arch=%ARCH% -e VERSION="%APPVEYOR_BUILD_VERSION%" -o gtest=%GTEST%
  - cmake .. -G "%VISUAL_STUDIO%" -A %PLATFORM%

build:
  project: $(APPVEYOR_BUILD_FOLDER)\build\WebSocketsAdapter.sln

after_build:
  - conan export-pkg ../WebSocketsAdapterTestUtilities/conanfile.py WebSocketsAdapterTestUtilities/%APPVEYOR_BUILD_VERSION%@systelab/stable -s build_type=%CONFIGURATION% -s compiler.toolset=%COMPILER_TOOLSET% -s arch=%ARCH% -o gtest=%GTEST%
  - conan test ../test_package/conanfile.py WebSocketsAdapterTestUtilities/%APPVEYOR_BUILD_VERSION%@systelab/stable -s build_type=%CONFIGURATION% -s compiler.toolset=%COMPILER_TOOLSET% -s arch=%ARCH% -o gtest=%GTEST%

artifacts:
  - path: 'build/lib/%CONFIGURATION%/WebSocketsAdapterTestUtilities.lib'
    name: WebSocketsAdapterTestUtilities.lib

deploy_script:
  - ps: >- 
      if($env:appveyor_repo_tag -eq 'True') {
        conan upload WebSocketsAdapterInterface/$env:appveyor_build_version@systelab/stable --all -r systelab-bintray --force
        conan upload WebSocketsAdapterTestUtilities/$env:appveyor_build_version@systelab/stable --all -r systelab-bintray --force
      } else {
        echo "Not uploading because this is not a tag build"
      }

